CREATE TABLE IF NOT EXISTS `apartaments` (
  `latitud` varchar(15) CHARACTER SET utf8mb4 COLLATE utf8mb4_unicode_ci NOT NULL,
  `longitud` varchar(15) CHARACTER SET utf8mb4 COLLATE utf8mb4_unicode_ci NOT NULL,
  `id` int(11) NOT NULL,
  `titulo` text CHARACTER SET utf8mb4 COLLATE utf8mb4_unicode_ci NOT NULL,
  `anunciante` text CHARACTER SET utf8mb4 COLLATE utf8mb4_unicode_ci NOT NULL,
  `descripcion` text CHARACTER SET utf8mb4 COLLATE utf8mb4_unicode_ci NOT NULL,
  `reformado` tinyint(1) NOT NULL DEFAULT '0',
  `telefonos` text CHARACTER SET utf8mb4 COLLATE utf8mb4_unicode_ci NOT NULL,
  `fecha` varchar(12) CHARACTER SET utf8mb4 COLLATE utf8mb4_unicode_ci NOT NULL DEFAULT '0',
  `tipo` text CHARACTER SET utf8mb4 COLLATE utf8mb4_unicode_ci NOT NULL,
  `precio` decimal(10,2) NOT NULL DEFAULT '0.00',
  `precioMetro` decimal(10,2) NOT NULL DEFAULT '0.00',
  `direccion` text CHARACTER SET utf8mb4 COLLATE utf8mb4_unicode_ci NOT NULL,
  `provincia` text CHARACTER SET utf8mb4 COLLATE utf8mb4_unicode_ci NOT NULL,
  `ciudad` text CHARACTER SET utf8mb4 COLLATE utf8mb4_unicode_ci NOT NULL,
  `calle` text CHARACTER SET utf8mb4 COLLATE utf8mb4_unicode_ci NOT NULL,
  `barrio` text CHARACTER SET utf8mb4 COLLATE utf8mb4_unicode_ci NOT NULL,
  `distrito` text CHARACTER SET utf8mb4 COLLATE utf8mb4_unicode_ci NOT NULL,
  `metrosCuadrados` decimal(10,2) NOT NULL DEFAULT '0.00',
  `bano` int(11) NOT NULL DEFAULT '0',
  `segundaMano` tinyint(1) NOT NULL DEFAULT '0',
  `armarioEmpotrado` tinyint(1) NOT NULL DEFAULT '0',
  `construidoEn` varchar(100) CHARACTER SET utf8mb4 COLLATE utf8mb4_unicode_ci NOT NULL DEFAULT '0',
  `cocinaEquipada` tinyint(1) NOT NULL DEFAULT '0',
  `amueblado` tinyint(1) NOT NULL DEFAULT '0',
  `cocinaEquipad` tinyint(1) NOT NULL DEFAULT '0',
  `certificacionEnergetica` text CHARACTER SET utf8mb4 COLLATE utf8mb4_unicode_ci NOT NULL,
  `planta` int(11) NOT NULL DEFAULT '0',
  `exterior` tinyint(1) NOT NULL DEFAULT '0',
  `interior` tinyint(1) NOT NULL DEFAULT '0',
  `ascensor` tinyint(1) NOT NULL DEFAULT '0',
  `aireAcondicionado` tinyint(1) NOT NULL DEFAULT '0',
  `habitaciones` int(11) NOT NULL DEFAULT '0',
  `balcon` tinyint(1) NOT NULL DEFAULT '0',
  `trastero` tinyint(1) NOT NULL DEFAULT '0',
  `metrosCuadradosUtiles` decimal(10,2) NOT NULL DEFAULT '0.00',
  `piscina` tinyint(1) NOT NULL DEFAULT '0',
  `jardin` tinyint(1) NOT NULL DEFAULT '0',
  `parking` tinyint(1) NOT NULL DEFAULT '0',
  `terraza` tinyint(1) NOT NULL DEFAULT '0',
  `calefaccionIndividual` text CHARACTER SET utf8mb4 COLLATE utf8mb4_unicode_ci NOT NULL,
  `movilidadReducida` tinyint(1) NOT NULL DEFAULT '0',
  `mascotas` tinyint(1) NOT NULL DEFAULT '0',
  PRIMARY KEY (`id`)
) ENGINE=MyISAM DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci;
