CREATE TABLE IF NOT EXISTS `apartaments` (
  `latitud` varchar(15) COLLATE utf8_spanish_ci NOT NULL,
  `longitud` varchar(15) COLLATE utf8_spanish_ci NOT NULL,
  `id` int(11) NOT NULL,
  `titulo` text COLLATE utf8_spanish_ci NOT NULL DEFAULT '0',
  `anunciante` text COLLATE utf8_spanish_ci NOT NULL DEFAULT '0',
  `descripcion` text COLLATE utf8_spanish_ci NOT NULL DEFAULT '0',
  `reformado` tinyint(1) NOT NULL DEFAULT '0',
  `telefonos` text COLLATE utf8_spanish_ci NOT NULL DEFAULT '0',
  `fecha` varchar(12) COLLATE utf8_spanish_ci NOT NULL DEFAULT '0',
  `tipo` text COLLATE utf8_spanish_ci NOT NULL DEFAULT '0',
  `precio` decimal(10,2) NOT NULL DEFAULT '0.00',
  `precioMetro` decimal(10,2) NOT NULL DEFAULT '0.00',
  `direccion` text COLLATE utf8_spanish_ci NOT NULL DEFAULT '0',
  `provincia` text COLLATE utf8_spanish_ci NOT NULL DEFAULT '0',
  `ciudad` text COLLATE utf8_spanish_ci NOT NULL DEFAULT '0',
  `calle` text COLLATE utf8_spanish_ci NOT NULL DEFAULT '0',
  `barrio` text COLLATE utf8_spanish_ci NOT NULL DEFAULT '0',
  `distrito` text COLLATE utf8_spanish_ci NOT NULL DEFAULT '0',
  `metrosCuadrados` decimal(10,2) NOT NULL DEFAULT '0.00',
  `bano` int(11) NOT NULL DEFAULT '0',
  `segundaMano` tinyint(1) NOT NULL DEFAULT '0',
  `armarioEmpotrado` tinyint(1) NOT NULL DEFAULT '0',
  `construidoEn` varchar(100) COLLATE utf8_spanish_ci NOT NULL DEFAULT '0',
  `cocinaEquipada` tinyint(1) NOT NULL DEFAULT '0',
  `amueblado` tinyint(1) NOT NULL DEFAULT '0',
  `cocinaEquipad` tinyint(1) NOT NULL DEFAULT '0',
  `certificacionEnergetica` text COLLATE utf8_spanish_ci NOT NULL DEFAULT '0',
  `planta` int(11) NOT NULL DEFAULT '0',
  `exterior` tinyint(1) NOT NULL DEFAULT '0',
  `interior` tinyint(1) NOT NULL DEFAULT '0',
  `ascensor` tinyint(1) NOT NULL DEFAULT '0',
  `aireAcondicionado` tinyint(1) NOT NULL DEFAULT '0',
  `habitaciones` int(11) NOT NULL DEFAULT '0',
  `balcon` tinyint(1) NOT NULL DEFAULT '0',
  `trastero` tinyint(1) NOT NULL DEFAULT '0',
  `metrosCuadradosUtiles` decimal(10,2) NOT NULL DEFAULT '0.00',
  `piscina` tinyint(1) NOT NULL DEFAULT '0',
  `jardin` tinyint(1) NOT NULL DEFAULT '0',
  `parking` tinyint(1) NOT NULL DEFAULT '0',
  `terraza` tinyint(1) NOT NULL DEFAULT '0',
  `calefaccionIndividual` text COLLATE utf8_spanish_ci NOT NULL DEFAULT '0',
  `movilidadReducida` tinyint(1) NOT NULL DEFAULT '0',
  `mascotas` tinyint(1) NOT NULL DEFAULT '0',
  PRIMARY KEY (`id`)
) ENGINE=MyISAM DEFAULT CHARSET=utf8 COLLATE=utf8_spanish_ci;